Repository Pensano-dev/aura-mobile-app, pull requests merged in 2024-03, with the labels that each got.

#43 Fix component name issue in frontend.
  backend/controllers/health.test.js
  frontend/src/screens/FacilitySelectorScreen.js
Labels: Urgent Bug Fix

#31 feat: FacilityForm component
  frontend/package.json
  frontend/src/components/Button/Button.js
  frontend/src/components/Button/ButtonStyles.js
  frontend/src/components/Facility/Facility.js
  frontend/src/components/FacilityForm/FacilityForm.js
  frontend/src/components/FacilityForm/FacilityFormStyles.js
  frontend/src/components/FacilityForm/mockData.js
  frontend/src/components/Modal/PopUpModal.js
  frontend/src/components/Modal/PopUpModalStyles.js
  frontend/src/components/placeholder.js
  frontend/src/screens/FacilitySelectorScreen.js
Labels: Approved

#42 Pj/feat/cafe controller with location
  README.md
  backend/controllers/cafeController.js
  backend/models/cafeModel.js
  backend/seed-data/cafeSeedData.js
Labels: Awaiting review

#74 chore: Linter + Prettier on BE
  backend/.eslintrc.js
  backend/.prettierrc
  backend/app.js
  backend/controllers/cafeController.js
  backend/controllers/health.test.js
  backend/controllers/healthController.js
  backend/index.js
  backend/models/cafeModel.js
  backend/models/healthModel.js
  backend/package-lock.json
  backend/package.json
  backend/routes/cafeRoutes.js
  backend/routes/healthRoutes.js
Labels: Approved

#73 Pj/chore/ci pipline investigation
  .github/workflows/apiJestTests.yml
  .github/workflows/apiPostmanTests.yml
Labels: Awaiting review

#94 Pj/fix/tidy up
  frontend/App.js
  frontend/src/components/Button/ButtonStyles.js
  frontend/src/components/Facility/Facility.js
  frontend/src/components/FacilityForm/FacilityForm.test.js
  frontend/src/components/FacilityForm/FacilityFormStyles.js
  frontend/src/components/MenuBar/MenuBar.js
  frontend/src/screens/FacilitySelectorScreen/FacilitySelectorScreen.js
  frontend/src/styles/globalColourVariables.js
  frontend/src/styles/globalStyleVariables.js
Labels: Awaiting review
